= Documentation Process
:sectnums:

== Documentation for a product change

=== Design stage
For any user-facing feature, the responsible PM/engineer should create a DOC ticket linked to the feature's design document.
The ticket should also specify a subject-matter expert (SME), who will be the primary point of contact for the Docs team to reach out for questions and feedback.

Docs team can offer feedback on the design from a user's perspective early in the feature design stage, as well as help with writing user-facing strings.

=== Release planning
Once it has been determined which the feature will be included in, PM/engineering should notify Documentation the release date that the feature documentation needs to be ready by.

At this stage, the feature should be relatively developed, and Docs team should assign a story point based on the estimated effort required to complete the ticket as well as a due date.

=== Draft for review
Documentation works with the engineer to produce a draft of the feature documentation.
This step may include the following:

* Tag the engineer in the ticket or design doc to ask clarifying questions
** It is okay to use private messaging to get answers especially if you have many follow-up questions.
* Schedule an interview with the engineer to conduct a more in-depth investigation of the feature or concepts behind the feature for complex changes

Draft for a new feature should be written in a separate branch of the Git repository.
The name of the branch should contain the ID of the ticket itself.

The draft should be finished _at least_ three business days before the due date of the doc ticket.
Leave a longer time window for reviews and revisions when the change is complex.

Once the draft is review-ready, open a pull request to merge the branch the draft is written in and invite the SME as well as a peer writer to review.
The writer should notify the reviewers that their reviews have been requested as many do not check their GitHub notifications.

For feature documents that are long and span an entire page or several pages, consider making a staging preview so that the reviewers have an easier time reading through your content.

=== SME review
Below are directions for the SME to review a documentation draft:

1. Read through the document.
Particularly, pay attention to the following:
+
--
* Is the document easy to read and skim?
* Is it missing any important information?
* Is critical information properly highlighted?
--
+
You are encouraged to offer any feedback you have.
As someone who is reading the draft for the first time, your perspective is valuable regardless of whether you think you are good at writing.
The writer will also use their judgement to decide whether to incorporate your suggestions.
2. Answer any questions that the writer asked regarding the document.
3. If you requested changes, review the edits after they are made.
When you think a doc is satisfactory, approve the Pull Request.

=== Peer review
Peer review happens in parallel to SME review.
The purpose of peer reviews is to minimize typos and mistakes, as well as ensure the documentation follow a consistent style.
As a peer reviewer, read through the document and pay attention to the following:

* Am I able to follow this document?
* Are there concepts or terms that are unclear to me that could be better linked?
* Are there typos or deviations from the link:style-guide.adoc[style guide]?

=== Publish
Once a draft has passed both reviews, it is ready to publish.
Merge the PR to publish the final draft.