= TigerGraph Documentation Site Build

This repository contains the Antora playbook used to build the TigerGraph documentation site.

== Install dependencies
To install dependencies, run:
[,bash]
----
npm install
----

== Build site locally
To build the site locally, run:
[,bash]
----
npm run build
----
The build will be available in the `build/` folder in the root directory. 

=== Build from your local content source repository
To have Anotora build site from your local content source repository, change the corresponding content source in the file `antora-playbook.yml` to point to your local git repository. 

See https://docs.antora.org/antora/2.3/playbook/content-source-url/#local-urls[Use local content repositories] on Antora's documentation. 

== Run a local server to view the build

To open the build:
[,bash]
----
$ npm i -g http-server
$ http-server build/site -c-1
----
Upon launching the command, the local address of the web server will be displayed in your terminal. You should see the following output in your terminal:

----
Starting up http-server, serving build/site
Available on:
  http://127.0.0.1:8080
  http://192.168.1.8:8080
Hit CTRL-C to stop the server
----