= Reviews

SME Reviews are critical to documentation quality. When a documentation draft is done, the new draft is submitted as a pull request, and will go through review before the new page is merged in.

== Who
The creator of the doc ticket should designate a reviewer at the time of creating the ticket.
If a reviewer is not designated,then the creator of the ticket bears the responsibility of reviewing the document.

== How
1. Read through the document. Particularly, pay attention to the following:
    * Is the document easy to read and skim?
    * Is it missing any important information?
    * Is critical information properly highlighted?
+
You are encouraged to offer any feedback you have.
As someone who is reading the draft for the first time, your perspective is valuable regardless of whether you think you are good at writing.
The writer will also use their judgement to decide whether to incorporate your suggestions.

2. Answer any questions that the writer asked regarding the document.

3. If you requested edits, review the edits after they are made.
When you think a doc is satisfactory, approve the Pull Request.

== When
Please review the draft within 48 hours of being assigned a review.
Without an approving review, a documentation edit cannot be published.

== Exceptions
The following edits can be merged without a review:

* Typos
* Quick factual fixes
* Reformatting content to be in line with the style guide