= TigerGraph Documentation
:navtitle: home
:page-role: home

Welcome to the TigerGraph documentation site!
Here you can find the reference materials, guides, and examples to develop your application and scale your analytics with the power of graph.

== Legacy documentation site
Our new documentation site provides you with improved organization, more accurate search, as well as faster page loading. However, it only contains documentation for TigerGraph 3.2 and later.

To access the documentation for TigerGraph 3.1 or earlier, please visit our https://docs.tigergraph.com/legacy[legacy documentation site].

== Navigation and switch versions
On the left side of any page you can find a navigation menu to any area of the documentation site.

To switch to a different version, click the version number you'd like to proceed with in the left-side navigation.

== Site areas
The TigerGraph documentation site consists of the following areas:

=== TigerGraph Server
xref:tigergraph-server:intro:introduction.adoc[TigerGraph Server documentation] provides guides and references for the core TigerGraph database server.
This area includes all the information for you to install, operate, maintain, and communicate with the TigerGraph database server programmatically.

=== GSQL Language Reference
The GSQL™ software program is the TigerGraph comprehensive environment for designing graph schemas, loading and managing data to build a graph, and querying the graph to perform data analysis.
In short, TigerGraph users do most of their work via the GSQL program.

To learn more about GSQL, see the xref:gsql-ref:intro:intro.adoc[GSQL Language Reference].

=== TigerGraph Graph Data Science Library
TigerGraph provides a collection of expertly written GSQL queries that efficiently implement common graph algorithms.
For more information, see xref:graph-ml:intro:overview.adoc[TigerGraph Graph Data Science Library].

=== GraphStudio and Admin Portal
GraphStudio and Admin Portal are TigerGraph's Graphic User Interfaces.

The TigerGraph GraphStudio™ UI (User Interface) provides an intuitive, browser-based interface that helps users get started quickly with graph-based application development tasks: designing a graph schema, creating a schema mapping, loading data, exploring the graph, and writing GSQL queries.

The TigerGraph Admin Portal is a browser-based devops tool which provides users an overview of a running TigerGraph system, from an application and infrastructure point of view.
It also allows the users to configure the TigerGraph system through a user-friendly interface.

To learn more about GraphStudio and Admin Portal, see xref:gui:graphstudio:overview.adoc[GraphStudio and Admin Portal].

=== TigerGraph Cloud
TigerGraph Cloud is a fully-managed cloud database built on the same TigerGraph Enterprise Server engine that is delivering the fastest and most scalable graph database.
TigerGraph Cloud handles all the complexity of deploying and managing your deployments on the cloud service provider of your choice (AWS, Azure, and GCP).

For more information, see xref:cloud:start:overview.adoc[].