= Compatibility and Migration Issues
:description:Description of compatibility and migration issues for users moving from previous versions of TigerGraph

[NOTE]
====
TigerGraph versioning branched after 3.10. From 3.10, you can upgrade either to 3.11 or to 4.1.
4.1 is not the successor to 3.11. They are two separate upgrade paths.
====

This section provides a historical record of feature changes between versions of TigerGraph which are not fully backwardly compatibility with earlier versions.
This includes:

* Discontinued features or options
* Behavioral changes which are not backwardly compatible

In addition to checking this list, check the xref:{page-component-version}@tigergraph-server:release-notes:index.adoc[Release Notes] for all the versions between your current version and your target version, for *deprecated features, known issues, new reserved words, or other behavioral changes*.

You may need to make migration changes to your TigerGraph application either before or after the upgrade.
For example, change the name of schema elements and refactor queries if a new reserved word was introduced.

If you have any questions or uncertainty, please contact TigerGraph Support.

See all the sections that pertain to your proposed migration.
For example, if you are considering migrating for 2.6 to 3.10, please see both pages.

* xref:home:compatibility:changes-from-tg2-to-tg3.adoc[]
* xref:home:compatibility:changes-among-tg3.adoc[]

For upgrade guidance, see the pages for your target version: 3.10 to 4.1 or within 4.x.  

* xref:home:compatibility:changes-among-tg4.adoc[]
* xref:home:compatibility:changes-from-tg3.10-to-tg4.1.adoc[]

