= TigerGraph Product Release and Lifecycle Policy
:description:This page explains TigerGraph's release and lifecycle policies.
:page-aliases: tigergraph-server:intro:release-process.adoc

Updated February 16, 2025

TigerGraph is committed to providing the most reliable, most secure, and highest performing enterprise-grade graph database.
Our product testing and versioning are designed to ensure stable, reliable software for production.

== Release Lifecycle Options

The TigerGraph database offers two tracks for the introduction of new features, offering users more choice:

=== LTS (Long Term Support) Versions

LTS versions offer a longer lifecyle, with extended maintenance.
Each LTS version offers

* Two (2) years of https://www.tigergraph.com/support-policy[technical support] and maintenance releases, starting from the GA release, followed by
* One (1) additional year of support-only assistance.
* A new LTS version is introduced approximately once a year.

=== Non-LTS Versions

A new non-LTS version is introduced approximately midway between LTS versions, e.g., about half a year after the most recent LTS version.
Non-LTS versions offer

* One (1) year of technical support and maintenance releases, followed by
* One (1) additional year of support-only assistance.


Non-LTS versions are designed for users who want earlier access to new features and can support more frequent upgrades.


== Lifecycle Stages and Release Types

A feature version goes through the following lifecycle stages, with 3 types of releases:

. Preview releases
. GA Release
. Maintenance releases

== Release Numbering and Terminology

TigerGraph version nomenclature generally follows https://semver.org/[semantic versioning].
Each release is a 3-number sequence in the format `<generation>.<feature>.<maintenance>`, with an optional suffix.

*Generation*

A generation represents a core architecture.
The generation remains stable for years.
Upgrading to a new generation may require some migration effort.

*Feature Version*

A feature version represents a set of product features.
When a new feature version is released, `<feature>` is incremented.
We strive for backward compatibility so that existing applications built on the previous feature version will continue to work without modification.

*Maintenance Release/Update*

A maintenance release fixes bugs and addresses security issues.
It does not introduce new functionality except when necessary to address problems.
The release cycle varies, depending on the number and severity of issues that have been detected and addressed.
The `<maintenance>` number follows the following conventions:

* The Preview release of a new feature version has `<maintenance>` = 0.
* The GA release of a new feature version has `<maintenance>` = 1.
* The subsequence maintenance releases have `<maintenance>` = 2, 3, ... as needed.

The following table summarized the release types and their naming.

.TigerGraph Release Types and Numbering
[width="100%",cols="<1,<3,<2",options="header",]
|===
| Release Type | Description | LTS Versions

| Preview
| Feature complete; seeking customer feedback and field testing
| X.Y.0-pre1, +
X.Y.0-pre2, ...

| GA
| Production-ready; features frozen; refined after customer feedback and field testing
| X.Y.1 LTS

| Maintenance
| Bug fixes, security updates
| X.Y.2, +
X.Y.3, ...
|===

== Release Deliverables

=== Feature Version

*Documentation:*
When a new feature version is introduced as a Preview relesase, the following documentation deliverables accompany the software release:

* A new branch in the TigerGraph online documentation for that product version (found at https://docs.tigergraph.com/https://docs.tigergraph.com/[docs.tigergraph.com])
* xref:tigergraph-server:release-notes:index.adoc[] section included in the TigerGraph online documentation.
* xref:tigergraph-server:installation:upgrade.adoc[Upgrade] section included in the TigerGraph online documentation.

*Notification:* Feature releases will be announced on our documentation website.
TigerGraph’s Customer Success team will also proactively share the release notes with existing customers.

*Upgrade Support:* Customers using an older version should refer to the upgrade section of the online documentation and should https://tigergraph.zendesk.com/hc/en-us/[open a support ticket] for assistance.

=== Maintenance Release

A Maintenance release provides fixes and improvements for a particular feature version.
The release cycle varies, depending on the number and severity of issues that have been detected and addressed.

*Documentation:*
We do not provide a new documentation branch for maintenance releases. Instead, we may update the corresponding feature version’s documents.

*Notification:* Maintenance releases are announced on our documentation website in a subsection of the Release Notes.
TigerGraph’s Customer Success team will proactively share the release notes with existing customers.

*Upgrade Support:* Users should refer to the xref:installation:upgrade.adoc[Upgrade] section of the documentation. Depending on the urgency of the patch, our Customer Success team may reach out to customers to discuss upgrading.

=== Patches

A patch is a limited scope update to a portion of the full product, to quickly address security vulnerabilities or critical functional issues.
Patches are released as the situation demands.
They could be universal, applicable to all users, or case-specific, applicable to systems deployed in a certain environment or configuration.

*Notification:* As a patch is being developed, the Customer Success team will reach out to the affected customers to inform them of the discovered issue and the immediate remediation plan while the patch is under development.

*Application of the patch:* After the patch is developed and has gone through the release certification process, the technical support team will email customers instructions on downloading and applying the patch.

*Post-release:* The patch will be merged in to future maintenance and feature releases. Given the additional time before those releases, the patch may be replaced with an improved solution to the problem.

=== Support

Customers who need assistance can open a support ticket at https://tigergraph.zendesk.com/hc/en-us/[TigerGraph's ZenDesk Portal].

== Managed Cloud Service

For customers who subscribe to TigerGraph’s Managed Cloud Service, our Cloud Engineering team will apply upgrades for backward compatible changes or One-Off patches transparently when the release is available or during the customer-notified system maintenance window (in situations requiring system downtime).

For releases with non-backward compatible changes, the TigerGraph Customer Success team will reach out to customers to discuss opt-out or opt-in choices.

Should the customer choose to opt-in, our Cloud Engineering team will coordinate and perform the upgrade for the customer.

